FROM python:3.8-slim-buster
RUN set -eux; \
	savedAptMark="$(apt-mark showmanual)"; \
	apt-get update; \
	apt-get install -y --no-install-recommends \	
		wget \
	; \
    wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb
RUN apt-get update && apt-get install -y dotnet-sdk-6.0
WORKDIR /
COPY requirements.txt .
ENV PIP_ROOT_USER_ACTION=ignore
RUN /usr/local/bin/python3 -m pip install --upgrade pip && pip3 install -r requirements.txt
